-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 11, 2026 at 11:21 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

-- HF_RESUME_MODEL=Qwen/Qwen2.5-7B-Instruct
-- HF_RESUME_TIMEOUT=18
-- RESUME_OCR_LANG=eng
--
-- Database: `updated_dev`
--

-- --------------------------------------------------------

--
-- Table structure for table `egc_recruitment_roles`
--

CREATE TABLE `egc_recruitment_roles` (
  `sno` int(11) NOT NULL,
  `jobrole_name` tinytext NOT NULL,
  `status` int(11) NOT NULL DEFAULT 0,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_by` int(11) DEFAULT NULL,
  `updated_at` datetime DEFAULT current_timestamp(),
  `role_description` text DEFAULT NULL,
  `mandatory_skills` text DEFAULT NULL,
  `preferred_skills` text DEFAULT NULL,
  `responsibilities` text DEFAULT NULL,
  `minimum_experience` decimal(5,2) DEFAULT NULL,
  `education_requirements` text DEFAULT NULL,
  `seniority` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

--
-- Dumping data for table `egc_recruitment_roles`
--

INSERT INTO `egc_recruitment_roles` (`sno`, `jobrole_name`, `status`, `created_by`, `created_at`, `updated_by`, `updated_at`, `role_description`, `mandatory_skills`, `preferred_skills`, `responsibilities`, `minimum_experience`, `education_requirements`, `seniority`) VALUES
(1, 'Business Development Executive', 0, 1, '2024-07-20 06:58:33', 1, '2026-08-25 00:50:27', 'Own revenue-oriented business development activities by identifying prospects, qualifying opportunities, building relationships, presenting solutions, negotiating commercial terms, and maintaining a healthy sales pipeline.', 'lead generation; prospecting; B2B sales; consultative selling; lead qualification; CRM; negotiation; proposal writing; relationship management; communication; presentation', 'LinkedIn Sales Navigator; HubSpot; Salesforce; Zoho CRM; Microsoft Excel; Google Workspace; proposal tools', 'Generate and qualify leads; conduct discovery calls and meetings; prepare proposals and quotations; follow up opportunities; update CRM; negotiate and close deals; coordinate handover to delivery; report pipeline and conversion metrics.', 1.00, 'Bachelor\'s degree or diploma in Business, Marketing, Communications, or related discipline; relevant sales experience may substitute for formal education.', 'Executive / Individual Contributor'),
(2, 'Senior Business Development  Executive', 0, 1, '2024-07-20 06:58:39', 1, '2026-08-25 00:50:27', 'Own revenue-oriented business development activities by identifying prospects, qualifying opportunities, building relationships, presenting solutions, negotiating commercial terms, and maintaining a healthy sales pipeline. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'lead generation; prospecting; B2B sales; consultative selling; lead qualification; CRM; negotiation; proposal writing; relationship management; communication; presentation', 'LinkedIn Sales Navigator; HubSpot; Salesforce; Zoho CRM; Microsoft Excel; Google Workspace; proposal tools', 'Generate and qualify leads; conduct discovery calls and meetings; prepare proposals and quotations; follow up opportunities; update CRM; negotiate and close deals; coordinate handover to delivery; report pipeline and conversion metrics.', 3.00, 'Bachelor\'s degree or diploma in Business, Marketing, Communications, or related discipline; relevant sales experience may substitute for formal education.', 'Senior / Individual Contributor'),
(3, 'Tele caller', 0, 1, '2024-07-20 06:58:45', 1, '2026-08-25 00:50:27', 'Provide responsive customer support, resolve service issues and maintain accurate case records while protecting customer experience and satisfaction.', 'customer service; communication; active listening; ticketing; problem solving; CRM; email/chat; conflict resolution; documentation', 'CRM; Zendesk/Freshdesk; Microsoft Excel; Google Workspace; telephony/chat systems', 'Handle inbound queries; troubleshoot issues; document interactions; escalate appropriately; follow SLAs; conduct follow-ups; collect feedback; maintain service quality metrics.', 1.00, 'Bachelor\'s degree or diploma in Business, Marketing, Communications, or related discipline; relevant sales experience may substitute for formal education.', 'Executive / Individual Contributor'),
(4, 'Marketing Executive', 0, 1, '2024-07-20 06:58:51', 1, '2026-08-25 00:50:27', 'Execute multi-channel marketing campaigns that increase qualified awareness, engagement and leads across digital and offline channels.', 'digital marketing; campaign management; social media; content marketing; SEO basics; Google Analytics; email marketing; lead generation; copywriting; Excel', 'Google Analytics 4; Google Ads; Meta Ads Manager; Canva; HubSpot; Mailchimp; Excel', 'Plan campaigns; create briefs and content calendars; coordinate creatives; manage social channels; track campaign performance; support lead generation; report CAC, CPL, CTR and conversion metrics.', 1.00, 'Bachelor\'s degree or diploma in Business, Marketing, Communications, or related discipline; relevant sales experience may substitute for formal education.', 'Executive / Individual Contributor'),
(5, 'Marketing Manager', 0, 1, '2024-07-20 06:58:57', 1, '2026-08-25 00:50:27', 'Lead marketing strategy and execution across acquisition, brand, content and performance channels with measurable pipeline and revenue outcomes.', 'marketing strategy; demand generation; performance marketing; SEO; SEM; analytics; campaign planning; budgeting; team leadership; CRM', 'Google Analytics 4; Google Ads; Meta Ads Manager; HubSpot; Salesforce; Canva; Excel; Looker Studio', 'Set marketing plans and KPIs; allocate budgets; lead campaigns; manage agencies and vendors; align marketing with sales; monitor funnel metrics; optimize CAC, CPL, conversion and ROI; coach team members.', 5.00, 'Bachelor\'s degree or diploma in Business, Marketing, Communications, or related discipline; relevant sales experience may substitute for formal education.', 'Manager'),
(6, 'Business Development Manager', 0, 1, '2024-07-20 06:59:04', 1, '2026-08-25 00:50:27', 'Own revenue-oriented business development activities by identifying prospects, qualifying opportunities, building relationships, presenting solutions, negotiating commercial terms, and maintaining a healthy sales pipeline. The manager level is expected to own planning, performance and team or stakeholder leadership.', 'lead generation; prospecting; B2B sales; consultative selling; lead qualification; CRM; negotiation; proposal writing; relationship management; communication; presentation', 'LinkedIn Sales Navigator; HubSpot; Salesforce; Zoho CRM; Microsoft Excel; Google Workspace; proposal tools', 'Generate and qualify leads; conduct discovery calls and meetings; prepare proposals and quotations; follow up opportunities; update CRM; negotiate and close deals; coordinate handover to delivery; report pipeline and conversion metrics.', 5.00, 'Bachelor\'s degree or diploma in Business, Marketing, Communications, or related discipline; relevant sales experience may substitute for formal education.', 'Manager'),
(7, 'HR Senior Executive', 0, 1, '2024-07-20 06:59:10', 1, '2026-08-25 00:50:27', 'Support end-to-end HR operations and employee lifecycle activities with emphasis on recruitment, documentation, employee relations, compliance and HR reporting. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'recruitment; sourcing; screening; interviewing; onboarding; employee records; HR policies; attendance; HRMS; Excel; communication', 'HRMS; ATS; Microsoft Excel; Microsoft Office; Google Workspace; payroll/attendance systems', 'Coordinate hiring and onboarding; maintain personnel records; support attendance and HR operations; handle employee queries; coordinate training; prepare HR reports; support policy and compliance activities.', 3.00, 'Bachelor\'s degree in Human Resources, Business Administration, Psychology, or related discipline; HR certification is a plus.', 'Senior / Individual Contributor'),
(8, 'HR Executive', 0, 1, '2024-07-20 06:59:18', 1, '2026-08-25 00:50:27', 'Execute day-to-day human resources operations including recruitment coordination, employee documentation, onboarding, HR records and employee support.', 'recruitment coordination; sourcing; screening; onboarding; HR documentation; employee records; HRMS; Excel; communication', 'ATS; HRMS; Microsoft Excel; Microsoft Office; Google Workspace', 'Schedule interviews; maintain candidate and employee records; coordinate onboarding; prepare HR letters; update HRMS; support attendance and leave administration; respond to employee queries.', 1.00, 'Bachelor\'s degree in Human Resources, Business Administration, Psychology, or related discipline; HR certification is a plus.', 'Executive / Individual Contributor'),
(9, 'HR Manager', 0, 1, '2024-07-20 06:59:32', 1, '2026-08-25 00:50:27', 'Lead HR operations and workforce initiatives covering recruitment, employee relations, policy implementation, performance, compliance and people reporting.', 'HR strategy; workforce planning; recruitment; employee relations; performance management; HR policies; compliance; HRMS; analytics; leadership', 'HRMS; ATS; Microsoft Excel; Power BI; Microsoft Office; payroll systems', 'Plan workforce needs; lead recruitment; manage employee relations; oversee onboarding and performance processes; maintain HR policies; monitor compliance; analyze people metrics; coach HR staff.', 5.00, 'Bachelor\'s degree in Human Resources, Business Administration, Psychology, or related discipline; HR certification is a plus.', 'Manager'),
(10, 'HR Recruiter', 0, 1, '2024-07-20 06:59:40', 1, '2026-08-25 00:50:27', 'Source, assess and coordinate candidates against approved company vacancies using structured screening, interview coordination and evidence-based candidate evaluation.', 'talent sourcing; Boolean search; screening; interviewing; ATS; candidate assessment; stakeholder communication; LinkedIn; recruitment analytics', 'ATS; LinkedIn Recruiter; Naukri; Indeed; Microsoft Excel; Google Workspace', 'Source candidates; screen resumes; conduct initial assessments; maintain candidate pipelines; coordinate interviews; capture feedback; communicate with hiring managers; track time-to-fill and funnel metrics.', 1.00, 'Bachelor\'s degree in Human Resources, Business Administration, Psychology, or related discipline; HR certification is a plus.', 'Executive / Individual Contributor'),
(11, 'Accounts Executive', 0, 1, '2024-07-20 06:59:46', 1, '2026-08-25 00:50:27', 'Maintain accurate accounting records and support transaction processing, reconciliations, invoicing, payables, receivables and financial reporting.', 'bookkeeping; journal entries; accounts payable; accounts receivable; bank reconciliation; GST basics; TDS basics; invoicing; Excel; Tally', 'Tally Prime; Zoho Books; QuickBooks; SAP/ERP; Microsoft Excel; GST portals', 'Record transactions; reconcile bank and ledger accounts; process invoices; follow up receivables; support payables; maintain vouchers; assist GST/TDS documentation; prepare periodic reports.', 1.00, 'Bachelor\'s degree in Commerce, Accounting, Finance, or related discipline; Tally/ERP certification preferred.', 'Executive / Individual Contributor'),
(12, 'Account Senior Executive', 0, 1, '2024-07-20 06:59:53', 1, '2026-08-25 00:50:27', 'Handle senior-level accounting operations including reconciliations, closing support, statutory documentation, payables/receivables and financial controls.', 'general ledger; reconciliations; month-end close; AP; AR; GST; TDS; audit support; ERP; Excel', 'Tally Prime; SAP; Oracle; Zoho Books; Microsoft Excel; GST portals', 'Review entries; perform reconciliations; support month-end closing; manage AP/AR aging; prepare schedules; coordinate audits; support statutory filings; improve accounting controls.', 3.00, 'Bachelor\'s degree in Commerce, Accounting, Finance, or related discipline; Tally/ERP certification preferred.', 'Senior / Individual Contributor'),
(13, 'Account Manager', 0, 1, '2024-07-20 07:00:01', 1, '2026-08-25 00:50:27', 'Oversee accounting operations, financial controls, reporting and statutory coordination while ensuring accurate and timely books of accounts. The manager level is expected to own planning, performance and team or stakeholder leadership.', 'financial accounting; month-end close; financial reporting; budgeting; GST; TDS; audit; internal controls; ERP; team leadership', 'SAP; Oracle; Tally Prime; Power BI; Microsoft Excel; ERP reporting', 'Lead accounting team; review ledgers and reconciliations; oversee closing; monitor cash, AP and AR; coordinate audits and statutory compliance; prepare management reports; strengthen controls.', 5.00, 'Bachelor\'s degree in Commerce, Accounting, Finance, or related discipline; Tally/ERP certification preferred.', 'Manager'),
(14, 'IT Executive', 0, 1, '2024-07-20 07:00:07', 1, '2026-08-25 00:50:27', 'Provide day-to-day IT support, endpoint administration, user access management, troubleshooting and basic infrastructure operations.', 'IT support; Windows; hardware; networking; troubleshooting; Active Directory; Microsoft 365; ticketing; cybersecurity basics', 'Microsoft 365; Active Directory; Windows Server; Jira Service Management; TeamViewer/AnyDesk; antivirus tools', 'Resolve user incidents; provision accounts and devices; troubleshoot hardware/software/network issues; manage tickets; support backups and endpoint security; maintain IT asset records.', 1.00, 'Relevant diploma, degree, trade qualification, or equivalent practical experience appropriate to the role.', 'Executive / Individual Contributor'),
(15, 'IT Senior Executive', 0, 1, '2024-07-20 07:00:15', 1, '2026-08-25 00:50:27', 'Own advanced IT support and endpoint/infrastructure operations, resolving complex incidents and maintaining secure, reliable workplace technology. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'advanced troubleshooting; Windows Server; Active Directory; Microsoft 365; networking; TCP/IP; DNS; DHCP; endpoint security; backup; ITIL', 'Microsoft 365; Active Directory; Windows Server; Intune; Jira Service Management; monitoring tools', 'Handle escalated incidents; administer users and endpoints; monitor infrastructure; maintain security controls; coordinate vendors; document changes; support backup and disaster recovery procedures.', 3.00, 'Relevant diploma, degree, trade qualification, or equivalent practical experience appropriate to the role.', 'Senior / Individual Contributor'),
(16, 'Admin Executive', 0, 1, '2024-07-20 07:00:24', 1, '2026-08-25 00:50:27', 'Manage administrative operations, records, vendor coordination, office services and day-to-day support for efficient business operations.', 'office administration; vendor management; documentation; procurement support; facilities; Excel; communication; coordination', 'Microsoft Office; Excel; Google Workspace; ERP/admin systems; procurement tools', 'Maintain records; coordinate vendors and facilities; support procurement; manage office supplies; schedule meetings; process administrative requests; prepare reports and ensure timely follow-up.', 1.00, 'Bachelor\'s degree or diploma in Business Administration, Operations, Commerce, or related discipline; equivalent experience may be considered.', 'Executive / Individual Contributor'),
(17, 'Java Developer', 0, 1, '2024-07-20 07:00:29', 1, '2026-08-25 00:50:27', 'Develop, test and maintain Java applications and APIs using maintainable object-oriented design, secure coding and database integration.', 'Java; OOP; Spring Boot; REST APIs; SQL; Git; Maven; JUnit; debugging; database design', 'Spring Boot; Hibernate/JPA; Maven; Git; Jenkins; Docker; MySQL/PostgreSQL', 'Implement features; design APIs; write unit tests; integrate databases; troubleshoot defects; review code; document changes; collaborate with analysts and QA; support deployment.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(18, 'Senior Java Developer', 0, 1, '2024-07-20 07:00:35', 1, '2026-08-25 00:50:27', 'Develop, test and maintain Java applications and APIs using maintainable object-oriented design, secure coding and database integration. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'Java; OOP; Spring Boot; REST APIs; SQL; Git; Maven; JUnit; debugging; database design', 'Spring Boot; Hibernate/JPA; Maven; Git; Jenkins; Docker; MySQL/PostgreSQL', 'Implement features; design APIs; write unit tests; integrate databases; troubleshoot defects; review code; document changes; collaborate with analysts and QA; support deployment.', 3.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Senior / Individual Contributor'),
(19, 'MATLAB Developer', 0, 1, '2024-07-20 07:00:42', 1, '2026-08-25 00:50:27', 'Develop MATLAB-based algorithms, simulations, numerical models and engineering analysis tools with reproducible validation.', 'MATLAB; Simulink; numerical methods; signal processing; data analysis; algorithms; scripting; modelling; debugging', 'MATLAB; Simulink; Stateflow; Python; Git', 'Develop algorithms and simulations; validate models; analyze data; document methods; optimize computational performance; collaborate with engineering teams; maintain reusable scripts.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(20, 'Senior MATLAB Developer', 0, 1, '2024-07-20 07:00:48', 1, '2026-08-25 00:50:27', 'Develop MATLAB-based algorithms, simulations, numerical models and engineering analysis tools with reproducible validation. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'MATLAB; Simulink; numerical methods; signal processing; data analysis; algorithms; scripting; modelling; debugging', 'MATLAB; Simulink; Stateflow; Python; Git', 'Develop algorithms and simulations; validate models; analyze data; document methods; optimize computational performance; collaborate with engineering teams; maintain reusable scripts.', 3.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Senior / Individual Contributor'),
(21, 'Python Developer', 0, 1, '2024-07-20 07:00:54', 1, '2026-08-25 00:50:27', 'Develop reliable Python applications, APIs, automation and data-processing components with strong testing and maintainability.', 'Python; Django/Flask/FastAPI; REST; SQL; Git; testing; APIs; OOP; automation; debugging', 'FastAPI; Django; Flask; Pytest; Docker; PostgreSQL; Redis; GitHub Actions', 'Build application features and APIs; write tests; integrate databases and services; automate workflows; optimize performance; review code; troubleshoot production issues.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(22, 'Senior Python Developer', 0, 1, '2024-07-20 07:01:00', 1, '2026-08-25 00:50:27', 'Develop reliable Python applications, APIs, automation and data-processing components with strong testing and maintainability. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'Python; Django/Flask/FastAPI; REST; SQL; Git; testing; APIs; OOP; automation; debugging', 'FastAPI; Django; Flask; Pytest; Docker; PostgreSQL; Redis; GitHub Actions', 'Build application features and APIs; write tests; integrate databases and services; automate workflows; optimize performance; review code; troubleshoot production issues.', 3.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Senior / Individual Contributor'),
(23, '.Net Developer', 0, 1, '2024-07-20 07:01:07', 1, '2026-08-25 00:50:27', 'Develop and maintain secure .NET applications, APIs and integrations using modern Microsoft development practices.', 'C#; .NET; ASP.NET Core; REST APIs; SQL Server; Entity Framework; Git; unit testing; debugging', 'Visual Studio; ASP.NET Core; Entity Framework Core; Azure; Docker; GitHub Actions; SQL Server', 'Build features and APIs; design database access; write tests; debug issues; perform code reviews; integrate third-party services; support deployment and production fixes.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(24, 'Senior .Net Developer', 0, 1, '2024-07-20 07:01:13', 1, '2026-08-25 00:50:27', 'Develop and maintain secure .NET applications, APIs and integrations using modern Microsoft development practices. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'C#; .NET; ASP.NET Core; REST APIs; SQL Server; Entity Framework; Git; unit testing; debugging', 'Visual Studio; ASP.NET Core; Entity Framework Core; Azure; Docker; GitHub Actions; SQL Server', 'Build features and APIs; design database access; write tests; debug issues; perform code reviews; integrate third-party services; support deployment and production fixes.', 3.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Senior / Individual Contributor'),
(25, 'PHP Developer', 0, 1, '2024-07-20 07:01:19', 1, '2026-08-25 00:50:27', 'Develop and maintain secure PHP web applications and APIs with strong database, testing and deployment practices.', 'PHP; Laravel; REST APIs; MySQL; OOP; Git; JavaScript; HTML; CSS; debugging; security', 'Laravel; Composer; MySQL; Redis; Docker; PHPUnit; GitHub Actions', 'Develop features; build APIs; optimize database queries; implement validation and security; write tests; fix defects; review code; support deployment and production incidents.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(26, 'Senior PHP Developer', 0, 1, '2024-07-20 07:01:25', 1, '2026-08-25 00:50:27', 'Develop and maintain secure PHP web applications and APIs with strong database, testing and deployment practices. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'PHP; Laravel; REST APIs; MySQL; OOP; Git; JavaScript; HTML; CSS; debugging; security', 'Laravel; Composer; MySQL; Redis; Docker; PHPUnit; GitHub Actions', 'Develop features; build APIs; optimize database queries; implement validation and security; write tests; fix defects; review code; support deployment and production incidents.', 3.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Senior / Individual Contributor'),
(27, 'Reactjs Developer', 0, 1, '2024-07-20 07:01:48', 1, '2026-08-25 00:50:27', 'Build responsive, accessible and maintainable React applications with reusable components, state management and API integration.', 'React; JavaScript/TypeScript; HTML; CSS; REST APIs; Git; state management; responsive UI; testing', 'React; TypeScript; Redux; Vite; Next.js; Jest; React Testing Library; GitHub Actions', 'Develop reusable components; integrate APIs; manage application state; optimize rendering; implement responsive interfaces; write tests; fix defects; collaborate with backend and design teams.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(28, 'Senior Reactjs Developer', 0, 1, '2024-07-20 07:01:54', 1, '2026-08-25 00:50:27', 'Build responsive, accessible and maintainable React applications with reusable components, state management and API integration. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'React; JavaScript/TypeScript; HTML; CSS; REST APIs; Git; state management; responsive UI; testing', 'React; TypeScript; Redux; Vite; Next.js; Jest; React Testing Library; GitHub Actions', 'Develop reusable components; integrate APIs; manage application state; optimize rendering; implement responsive interfaces; write tests; fix defects; collaborate with backend and design teams.', 3.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Senior / Individual Contributor'),
(29, 'Android Developer', 0, 1, '2024-07-20 07:01:59', 1, '2026-08-25 00:50:27', 'Develop, test and maintain native Android applications with robust UI, API integration, performance and lifecycle handling.', 'Kotlin; Java; Android SDK; Jetpack; REST APIs; SQLite/Room; Git; debugging; testing', 'Android Studio; Kotlin Coroutines; Jetpack Compose; Retrofit; Room; Firebase; GitHub Actions', 'Implement Android features; integrate APIs; manage local data; handle lifecycle and performance; write tests; debug crashes; publish releases; monitor production issues.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(30, 'Senior Android Developer', 0, 1, '2024-07-20 07:02:04', 1, '2026-08-25 00:50:27', 'Develop, test and maintain native Android applications with robust UI, API integration, performance and lifecycle handling. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'Kotlin; Java; Android SDK; Jetpack; REST APIs; SQLite/Room; Git; debugging; testing', 'Android Studio; Kotlin Coroutines; Jetpack Compose; Retrofit; Room; Firebase; GitHub Actions', 'Implement Android features; integrate APIs; manage local data; handle lifecycle and performance; write tests; debug crashes; publish releases; monitor production issues.', 3.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Senior / Individual Contributor'),
(31, 'Flutter Developer', 0, 1, '2024-07-20 07:02:11', 1, '2026-08-25 00:50:27', 'Build cross-platform mobile applications with Flutter using maintainable architecture, responsive UI and reliable API integration.', 'Dart; Flutter; REST APIs; state management; Git; mobile UI; debugging; testing', 'Flutter; Riverpod/Bloc; Firebase; Android Studio; Xcode; GitHub Actions', 'Develop reusable widgets; integrate APIs; implement state management; optimize mobile performance; test on devices; fix defects; prepare Android/iOS releases.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(32, 'Senior Flutter Developer', 0, 1, '2024-07-20 07:02:16', 1, '2026-08-25 00:50:27', 'Build cross-platform mobile applications with Flutter using maintainable architecture, responsive UI and reliable API integration. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'Dart; Flutter; REST APIs; state management; Git; mobile UI; debugging; testing', 'Flutter; Riverpod/Bloc; Firebase; Android Studio; Xcode; GitHub Actions', 'Develop reusable widgets; integrate APIs; implement state management; optimize mobile performance; test on devices; fix defects; prepare Android/iOS releases.', 3.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Senior / Individual Contributor'),
(33, 'Customer Care Executive', 0, 1, '2024-07-20 07:02:22', 1, '2026-08-25 00:50:27', 'Provide responsive customer support, resolve service issues and maintain accurate case records while protecting customer experience and satisfaction.', 'customer service; communication; active listening; ticketing; problem solving; CRM; email/chat; conflict resolution; documentation', 'CRM; Zendesk/Freshdesk; Microsoft Excel; Google Workspace; telephony/chat systems', 'Handle inbound queries; troubleshoot issues; document interactions; escalate appropriately; follow SLAs; conduct follow-ups; collect feedback; maintain service quality metrics.', 1.00, 'Bachelor\'s degree or diploma in Business, Marketing, Communications, or related discipline; relevant sales experience may substitute for formal education.', 'Executive / Individual Contributor'),
(34, 'Process Coordinator', 0, 1, '2024-07-20 07:02:28', 1, '2026-08-25 00:50:27', 'Coordinate operational processes, schedules, documentation and cross-team follow-ups to ensure timely execution and accurate reporting.', 'process coordination; documentation; scheduling; Excel; reporting; stakeholder coordination; SLA tracking; problem solving', 'Microsoft Excel; Google Sheets; Microsoft Teams; project management tools; ERP', 'Track process queues; coordinate stakeholders; maintain records; monitor SLAs; prepare reports; identify delays; escalate exceptions; improve process consistency.', 1.00, 'Bachelor\'s degree or diploma in Business Administration, Operations, Commerce, or related discipline; equivalent experience may be considered.', 'Executive / Individual Contributor'),
(35, 'Content Writer', 0, 1, '2024-07-20 07:02:33', 1, '2026-08-25 00:50:27', 'Create accurate, audience-focused written content for websites, marketing, product, SEO and business communications.', 'content writing; copywriting; research; SEO writing; editing; proofreading; English grammar; CMS; storytelling', 'WordPress; Google Docs; Grammarly; Ahrefs/SEMrush; Canva; CMS tools', 'Research topics; write and edit content; optimize for search intent; maintain editorial standards; collaborate with SEO/design teams; update content based on performance.', 1.00, 'Bachelor\'s degree in English, Journalism, Communications, Marketing, or related discipline; strong portfolio preferred.', 'Executive / Individual Contributor'),
(36, 'Senior Content Writer', 0, 1, '2024-07-20 07:02:40', 1, '2026-08-25 00:50:27', 'Create accurate, audience-focused written content for websites, marketing, product, SEO and business communications. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'content writing; copywriting; research; SEO writing; editing; proofreading; English grammar; CMS; storytelling', 'WordPress; Google Docs; Grammarly; Ahrefs/SEMrush; Canva; CMS tools', 'Research topics; write and edit content; optimize for search intent; maintain editorial standards; collaborate with SEO/design teams; update content based on performance.', 3.00, 'Bachelor\'s degree in English, Journalism, Communications, Marketing, or related discipline; strong portfolio preferred.', 'Senior / Individual Contributor'),
(37, 'Journal Coordinator', 0, 1, '2024-07-20 07:02:46', 1, '2026-08-25 00:50:27', 'Coordinate journal or publication workflows including manuscript tracking, author communication, editorial schedules and quality-controlled documentation.', 'journal workflow; editorial coordination; manuscript tracking; author communication; proofreading; documentation; deadline management', 'Editorial Manager/ScholarOne; Microsoft Office; Google Workspace; plagiarism checking tools', 'Track submissions; coordinate reviewers and authors; maintain publication records; monitor deadlines; prepare correspondence; support editorial quality checks; update workflow reports.', 1.00, 'Bachelor\'s degree in English, Journalism, Communications, Marketing, or related discipline; strong portfolio preferred.', 'Executive / Individual Contributor'),
(38, 'Coordinator', 0, 1, '2024-07-20 07:02:54', 1, '2026-08-25 00:50:27', 'Coordinate assigned operational activities, schedules, records and stakeholder follow-ups to keep workstreams on time and documented.', 'coordination; communication; scheduling; documentation; Excel; reporting; follow-up; organization', 'Microsoft Office; Excel; Google Workspace; Teams; project management tools', 'Maintain trackers; schedule meetings; coordinate tasks; follow up actions; prepare reports; update records; identify blockers; escalate unresolved issues.', 1.00, 'Bachelor\'s degree or diploma in Business Administration, Operations, Commerce, or related discipline; equivalent experience may be considered.', 'Executive / Individual Contributor'),
(39, 'SEO Executive', 0, 1, '2024-07-20 07:03:01', 1, '2026-08-25 00:50:27', 'Execute technical and content SEO activities to improve organic visibility, qualified traffic and search performance.', 'SEO; keyword research; on-page SEO; technical SEO basics; Google Search Console; analytics; content optimization; link building', 'Google Search Console; Google Analytics 4; Ahrefs; Semrush; Screaming Frog; WordPress', 'Perform keyword research; optimize pages and metadata; audit technical issues; monitor rankings and traffic; coordinate content; build quality links; report SEO KPIs.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(40, 'Senior SEO Executive', 0, 1, '2024-07-20 07:03:08', 1, '2026-08-25 00:50:27', 'Execute technical and content SEO activities to improve organic visibility, qualified traffic and search performance. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'SEO; keyword research; on-page SEO; technical SEO basics; Google Search Console; analytics; content optimization; link building', 'Google Search Console; Google Analytics 4; Ahrefs; Semrush; Screaming Frog; WordPress', 'Perform keyword research; optimize pages and metadata; audit technical issues; monitor rankings and traffic; coordinate content; build quality links; report SEO KPIs.', 3.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Senior / Individual Contributor'),
(41, 'Project Manager', 0, 1, '2024-07-20 07:03:13', 1, '2026-08-25 00:50:27', 'Plan and lead projects from initiation through delivery, managing scope, schedule, resources, risks, stakeholders and quality.', 'project management; planning; risk management; stakeholder management; Agile; Scrum; budgeting; reporting; leadership', 'Jira; Confluence; Microsoft Project; Asana; Trello; Microsoft Excel; Teams', 'Define scope; create plans; coordinate teams; track milestones; manage risks/issues; communicate status; control changes; coordinate releases; close projects and capture lessons learned.', 5.00, 'Bachelor\'s degree in Computer Science, Engineering, Business, or related discipline; project management certification is a plus.', 'Manager'),
(42, 'Software Tester', 0, 1, '2024-07-20 07:03:18', 1, '2026-08-25 00:50:27', 'Design and execute software tests to identify defects, validate requirements and improve product quality across functional and regression cycles.', 'manual testing; test cases; regression testing; API testing; SQL; defect tracking; SDLC; Agile; test documentation', 'Jira; TestRail; Postman; Selenium; JMeter; SQL; Browser DevTools', 'Analyze requirements; design test cases; execute functional/regression tests; log defects; validate fixes; perform API/database checks; report quality risks; support releases.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(43, 'Senior Software Tester', 0, 1, '2024-07-20 07:03:24', 1, '2026-08-25 00:50:27', 'Design and execute software tests to identify defects, validate requirements and improve product quality across functional and regression cycles. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'manual testing; test cases; regression testing; API testing; SQL; defect tracking; SDLC; Agile; test documentation', 'Jira; TestRail; Postman; Selenium; JMeter; SQL; Browser DevTools', 'Analyze requirements; design test cases; execute functional/regression tests; log defects; validate fixes; perform API/database checks; report quality risks; support releases.', 3.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Senior / Individual Contributor'),
(44, 'Software Faculty', 0, 1, '2024-07-20 07:03:30', 1, '2026-08-25 00:50:27', 'Deliver practical software development instruction, mentoring learners through programming concepts, projects, debugging and industry-oriented practices.', 'programming; teaching; curriculum planning; mentoring; Java/Python/.NET/web fundamentals; problem solving; assessment', 'VS Code; IntelliJ/Visual Studio; Git; LMS; online coding platforms', 'Prepare lessons; conduct labs; mentor projects; assess assignments; explain programming concepts; review code; track learner progress; update course material.', 2.00, 'Bachelor\'s degree or diploma in the relevant technical discipline; teaching/training certification preferred.', 'Professional / Trainer'),
(45, 'Senior Software Faculty', 0, 1, '2024-07-20 07:03:35', 1, '2026-08-25 00:50:27', 'Deliver practical software development instruction, mentoring learners through programming concepts, projects, debugging and industry-oriented practices. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'programming; teaching; curriculum planning; mentoring; Java/Python/.NET/web fundamentals; problem solving; assessment', 'VS Code; IntelliJ/Visual Studio; Git; LMS; online coding platforms', 'Prepare lessons; conduct labs; mentor projects; assess assignments; explain programming concepts; review code; track learner progress; update course material.', 3.00, 'Bachelor\'s degree or diploma in the relevant technical discipline; teaching/training certification preferred.', 'Senior / Individual Contributor'),
(46, 'Networking Faculty', 0, 1, '2024-07-20 07:03:40', 1, '2026-08-25 00:50:27', 'Deliver practical networking education covering protocols, routing, switching, troubleshooting, security and network administration fundamentals.', 'TCP/IP; OSI; routing; switching; subnetting; DNS; DHCP; VLAN; network security; troubleshooting', 'Cisco Packet Tracer; Wireshark; GNS3; Cisco IOS; Linux networking tools', 'Teach networking concepts; conduct labs; configure simulations; assess practical skills; troubleshoot lab issues; prepare exercises; mentor learners toward industry certifications.', 2.00, 'Bachelor\'s degree or diploma in the relevant technical discipline; teaching/training certification preferred.', 'Professional / Trainer'),
(47, 'Senior Networking Faculty', 0, 1, '2024-07-20 07:03:45', 1, '2026-08-25 00:50:27', 'Deliver practical networking education covering protocols, routing, switching, troubleshooting, security and network administration fundamentals. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'TCP/IP; OSI; routing; switching; subnetting; DNS; DHCP; VLAN; network security; troubleshooting', 'Cisco Packet Tracer; Wireshark; GNS3; Cisco IOS; Linux networking tools', 'Teach networking concepts; conduct labs; configure simulations; assess practical skills; troubleshoot lab issues; prepare exercises; mentor learners toward industry certifications.', 3.00, 'Bachelor\'s degree or diploma in the relevant technical discipline; teaching/training certification preferred.', 'Senior / Individual Contributor'),
(48, 'Embedded Engineer', 0, 1, '2024-07-20 07:03:51', 1, '2026-08-25 00:50:27', 'Design, develop and debug embedded firmware and hardware-integrated software for reliable real-time or resource-constrained systems.', 'C/C++; microcontrollers; embedded C; UART; SPI; I2C; CAN; RTOS; debugging; electronics fundamentals', 'STM32CubeIDE; Keil; Arduino/ESP32; JTAG/SWD; Git; logic analyzer; oscilloscopes', 'Develop firmware; integrate peripherals; debug hardware/software issues; implement communication protocols; optimize memory/timing; write tests; document interfaces and releases.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(49, 'Senior Embedded Engineer', 0, 1, '2024-07-20 07:03:56', 1, '2026-08-25 00:50:27', 'Design, develop and debug embedded firmware and hardware-integrated software for reliable real-time or resource-constrained systems. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'C/C++; microcontrollers; embedded C; UART; SPI; I2C; CAN; RTOS; debugging; electronics fundamentals', 'STM32CubeIDE; Keil; Arduino/ESP32; JTAG/SWD; Git; logic analyzer; oscilloscopes', 'Develop firmware; integrate peripherals; debug hardware/software issues; implement communication protocols; optimize memory/timing; write tests; document interfaces and releases.', 3.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Senior / Individual Contributor'),
(50, 'Embedded Faculty', 0, 1, '2024-07-20 07:04:01', 1, '2026-08-25 00:50:27', 'Teach embedded systems through practical firmware, microcontroller, electronics and interfacing projects.', 'embedded C; microcontrollers; C/C++; UART; SPI; I2C; sensors; RTOS basics; electronics; teaching', 'Arduino IDE; STM32CubeIDE; Keil; Proteus; PlatformIO; Git', 'Prepare labs; teach embedded programming; guide hardware interfacing projects; troubleshoot student builds; assess projects; maintain lab materials and safety practices.', 2.00, 'Bachelor\'s degree or diploma in the relevant technical discipline; teaching/training certification preferred.', 'Professional / Trainer'),
(51, 'Senior Embedded Faculty', 0, 1, '2024-07-20 07:04:06', 1, '2026-08-25 00:50:27', 'Teach embedded systems through practical firmware, microcontroller, electronics and interfacing projects. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'embedded C; microcontrollers; C/C++; UART; SPI; I2C; sensors; RTOS basics; electronics; teaching', 'Arduino IDE; STM32CubeIDE; Keil; Proteus; PlatformIO; Git', 'Prepare labs; teach embedded programming; guide hardware interfacing projects; troubleshoot student builds; assess projects; maintain lab materials and safety practices.', 3.00, 'Bachelor\'s degree or diploma in the relevant technical discipline; teaching/training certification preferred.', 'Senior / Individual Contributor'),
(52, 'Freelancer Faculty', 0, 1, '2024-07-20 07:04:13', 1, '2026-08-25 00:50:27', 'Deliver flexible technical training or mentoring engagements with clear learning outcomes, project-based instruction and client-focused communication.', 'technical training; curriculum design; mentoring; communication; project guidance; assessment; time management', 'LMS; Zoom/Teams; GitHub; Google Workspace; coding platforms', 'Define learning objectives; deliver sessions; mentor projects; assess progress; maintain materials; communicate schedules and outcomes; adapt training to learner needs.', 2.00, 'Bachelor\'s degree or diploma in the relevant technical discipline; teaching/training certification preferred.', 'Professional / Trainer'),
(53, 'Freelancer Developer', 0, 1, '2024-07-20 07:04:18', 1, '2026-08-25 00:50:27', 'Deliver software projects independently or with distributed teams, from requirements and implementation through testing, deployment and handover.', 'software development; client communication; requirements; Git; APIs; databases; testing; deployment; documentation', 'GitHub/GitLab; Docker; cloud platforms; CI/CD; Jira/Trello; VS Code', 'Clarify requirements; estimate work; implement features; test and deploy; communicate progress; manage changes; document solutions; provide maintenance and handover.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(54, 'UI Designer', 0, 1, '2024-07-20 07:04:24', 1, '2026-08-25 00:50:27', 'Design intuitive, accessible and consistent user interfaces based on user needs, product requirements and usability principles.', 'UI design; UX fundamentals; wireframing; prototyping; typography; color; responsive design; design systems; usability', 'Figma; FigJam; Adobe XD; Photoshop; Illustrator; design systems', 'Create user flows and wireframes; design high-fidelity screens; maintain components; prototype interactions; collaborate with product/development; conduct usability reviews; prepare handoff specs.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(55, 'Senior UI Designer', 0, 1, '2024-07-20 07:04:30', 1, '2026-08-25 00:50:27', 'Design intuitive, accessible and consistent user interfaces based on user needs, product requirements and usability principles. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'UI design; UX fundamentals; wireframing; prototyping; typography; color; responsive design; design systems; usability', 'Figma; FigJam; Adobe XD; Photoshop; Illustrator; design systems', 'Create user flows and wireframes; design high-fidelity screens; maintain components; prototype interactions; collaborate with product/development; conduct usability reviews; prepare handoff specs.', 3.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Senior / Individual Contributor'),
(56, 'Graphic Designer', 0, 1, '2024-07-20 07:04:40', 1, '2026-08-25 00:50:27', 'Create high-quality visual assets for digital and print communication while maintaining brand consistency and production standards.', 'graphic design; typography; layout; branding; visual communication; image editing; print/digital production', 'Adobe Photoshop; Illustrator; InDesign; Figma; Canva; After Effects', 'Develop creative concepts; produce social and marketing assets; prepare print/digital files; maintain brand guidelines; collaborate with marketing; revise designs based on feedback.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(57, 'Senior Graphic Designer', 0, 1, '2024-07-20 07:04:48', 1, '2026-08-25 00:50:27', 'Create high-quality visual assets for digital and print communication while maintaining brand consistency and production standards. The senior level is expected to handle complex work, mentor peers and contribute to process or technical decisions.', 'graphic design; typography; layout; branding; visual communication; image editing; print/digital production', 'Adobe Photoshop; Illustrator; InDesign; Figma; Canva; After Effects', 'Develop creative concepts; produce social and marketing assets; prepare print/digital files; maintain brand guidelines; collaborate with marketing; revise designs based on feedback.', 3.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Senior / Individual Contributor'),
(58, 'WordPress Developer', 0, 1, '2024-07-20 07:04:52', 1, '2026-08-25 00:50:27', 'Build, customize and maintain secure WordPress websites, themes, plugins and integrations with attention to performance and SEO.', 'WordPress; PHP; HTML; CSS; JavaScript; MySQL; REST APIs; plugins; themes; SEO; security', 'WordPress; WooCommerce; Elementor; Gutenberg; PHP; MySQL; Git; WP-CLI', 'Develop and customize sites; configure themes/plugins; integrate APIs; optimize performance; implement backups/security; fix defects; manage content workflows; support deployments.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(59, 'Management Support', 0, 1, '2024-07-20 07:04:57', 1, '2026-08-25 00:50:27', 'Provide executive and management support through scheduling, documentation, reporting, coordination and confidential administrative follow-through.', 'executive support; scheduling; documentation; reporting; communication; Excel; confidentiality; coordination', 'Microsoft Office; Excel; PowerPoint; Outlook; Google Workspace; Teams', 'Manage calendars; prepare documents and reports; coordinate meetings; track action items; handle correspondence; maintain confidential records; coordinate internal and external stakeholders.', 1.00, 'Bachelor\'s degree or diploma in Business Administration, Operations, Commerce, or related discipline; equivalent experience may be considered.', 'Executive / Individual Contributor');
INSERT INTO `egc_recruitment_roles` (`sno`, `jobrole_name`, `status`, `created_by`, `created_at`, `updated_by`, `updated_at`, `role_description`, `mandatory_skills`, `preferred_skills`, `responsibilities`, `minimum_experience`, `education_requirements`, `seniority`) VALUES
(60, 'Driver', 0, 1, '2024-07-20 07:05:01', 1, '2026-08-25 00:50:27', 'Provide safe, punctual and responsible transportation while maintaining the assigned vehicle, route records and compliance with traffic and company requirements.', 'safe driving; route planning; vehicle checks; navigation; time management; documentation; basic vehicle maintenance; customer service', 'Google Maps; navigation apps; vehicle tracking systems', 'Perform pre-trip checks; transport personnel or goods safely; follow routes and schedules; maintain vehicle cleanliness; record trips; report defects; comply with traffic and safety requirements.', 2.00, 'Valid commercial driving licence as applicable; secondary education preferred; clean driving record.', 'Skilled / Operational'),
(61, 'Electrician', 0, 1, '2024-07-20 07:05:07', 1, '2026-08-25 00:50:27', 'Install, maintain and troubleshoot electrical systems and equipment safely in accordance with applicable standards, drawings and site procedures.', 'electrical wiring; troubleshooting; panels; motors; cabling; testing; safety; preventive maintenance; reading schematics', 'Multimeter; insulation tester; clamp meter; electrical drawings; PPE; maintenance CMMS', 'Inspect and maintain electrical systems; diagnose faults; perform installations and repairs; test circuits; document work; follow lockout/tagout and electrical safety procedures.', 2.00, 'ITI/Diploma in Electrical or equivalent trade qualification; relevant electrical safety certification preferred.', 'Skilled / Operational'),
(62, 'Others', 0, 1, '2024-07-20 07:05:11', 1, '2026-08-25 00:50:27', 'General / Other Role', 'Relevant role-specific skills and transferable skills demonstrated by the candidate; adaptability; communication; problem solving; basic digital literacy', 'Microsoft Office; Google Workspace; role-specific tools', 'Perform duties defined by the approved vacancy; maintain accurate records; follow procedures; collaborate with stakeholders; meet quality, safety and delivery expectations.', 1.00, 'Relevant diploma, degree, trade qualification, or equivalent practical experience appropriate to the role.', 'Role-dependent'),
(63, 'Front Office Executive', 0, 3, '2024-07-30 08:34:21', 1, '2026-08-25 00:50:27', 'Manage front-desk operations, visitor handling, calls, correspondence and administrative coordination while providing a professional first point of contact.', 'front office; reception; communication; customer service; telephone handling; scheduling; documentation; MS Office', 'Microsoft Office; Outlook; Google Workspace; visitor management systems; Excel', 'Welcome visitors; manage calls and inquiries; coordinate meetings; maintain visitor records; handle correspondence; support office administration; escalate service issues.', 1.00, 'Bachelor\'s degree or diploma in Business Administration, Operations, Commerce, or related discipline; equivalent experience may be considered.', 'Executive / Individual Contributor'),
(64, 'Software Developer', 0, 1, '2024-08-01 06:00:03', 1, '2026-08-25 00:50:27', 'Design, develop, test and maintain software applications and services using sound engineering practices and collaborative delivery.', 'programming; OOP; data structures; algorithms; APIs; SQL; Git; testing; debugging; software design', 'Git; Docker; CI/CD; VS Code/IDE; relational databases; cloud platforms; testing frameworks', 'Analyze requirements; implement features; design APIs; write tests; review code; troubleshoot defects; optimize applications; document changes; support production releases.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(65, 'Full Stack Developer', 0, 3, '2024-08-08 10:49:06', 1, '2026-08-25 00:50:27', 'Build end-to-end web applications across frontend, backend, databases and integrations with secure, scalable and maintainable architecture.', 'JavaScript/TypeScript; React; PHP/Laravel or Node.js; REST APIs; SQL; Git; HTML; CSS; authentication; testing', 'React; Laravel/Node.js; MySQL/PostgreSQL; Redis; Docker; GitHub Actions; cloud services', 'Develop frontend and backend features; design APIs and schemas; integrate services; implement authentication; optimize performance; test; review code; deploy and support applications.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(66, 'Business Analyst ', 0, 3, '2024-08-13 11:01:00', 1, '2026-08-25 00:50:27', 'Translate business needs into clear requirements, process improvements and actionable analysis that align stakeholders and delivery teams.', 'requirements analysis; stakeholder management; process mapping; user stories; acceptance criteria; data analysis; SQL basics; documentation', 'Jira; Confluence; Microsoft Excel; Power BI; Visio; SQL tools', 'Gather requirements; map current/future processes; document user stories; define acceptance criteria; analyze data; facilitate stakeholder sessions; support UAT; track requirements through delivery.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(67, 'DEVOPS Engineer', 0, 3, '2024-08-14 05:09:31', 1, '2026-08-25 00:50:27', 'Automate software delivery and infrastructure operations to improve deployment reliability, observability, scalability and recovery.', 'Linux; cloud; Docker; Kubernetes; CI/CD; Git; infrastructure as code; networking; monitoring; scripting; security', 'AWS/Azure/GCP; Docker; Kubernetes; Terraform; Jenkins/GitHub Actions; Prometheus; Grafana; Ansible', 'Build CI/CD pipelines; provision infrastructure; automate deployments; manage containers; monitor systems; improve reliability; manage secrets and access; support incident response and recovery.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(68, 'Mobile App & IOS Developer', 0, 3, '2024-12-09 05:01:14', 1, '2026-08-25 00:50:27', 'Develop and maintain mobile applications with emphasis on iOS engineering, API integration, usability, performance and reliable release management.', 'Swift; iOS SDK; UIKit/SwiftUI; REST APIs; JSON; Git; testing; mobile architecture; debugging', 'Xcode; SwiftUI; UIKit; Firebase; Fastlane; TestFlight; GitHub Actions', 'Develop iOS features; integrate APIs; manage app state and persistence; optimize performance; write tests; troubleshoot crashes; prepare App Store/TestFlight releases; monitor production issues.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor'),
(69, 'Data Analyst', 0, 3, '2025-01-08 20:53:13', 1, '2026-08-25 00:50:27', 'Transform operational and business data into accurate insights, dashboards and recommendations using statistical reasoning and clear communication.', 'SQL; Excel; data cleaning; statistics; visualization; KPI analysis; Power BI/Tableau; Python basics; reporting', 'Power BI; Tableau; Excel; SQL; Python/pandas; Google Sheets; Looker Studio', 'Collect and clean data; write queries; define KPIs; build dashboards; analyze trends and anomalies; validate data quality; communicate findings; support business decisions.', 1.00, 'Bachelor\'s degree or diploma in Computer Science, IT, Engineering, Design, Analytics, or a related discipline; equivalent practical experience may be considered.', 'Executive / Individual Contributor');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `egc_recruitment_roles`
--
ALTER TABLE `egc_recruitment_roles`
  ADD PRIMARY KEY (`sno`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `egc_recruitment_roles`
--
ALTER TABLE `egc_recruitment_roles`
  MODIFY `sno` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=70;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
